/***************************************************************************************
 * Copyright © 2024 Haitian Jiang
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the “Software”), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or
 * sell copies of the Software, and to permit persons to whom
 * the Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall
 * be included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 **************************************************************************************/

#include <common.h>

/* Add the config macro in Kconfig or delete it. */
#ifdef CONFIG_VIM_AUTO_JUMP

#define VIM_CMD_LEN 512

static char *vim_server_name = "VIM";
static char *vim_script_name = "disasm-highlight.vim";
static char cmd[VIM_CMD_LEN] = {0};

static inline void vim_print_error_info(const char *server_name)
{
    printf(ANSI_FG_CYAN "Warning: the vim server %s is not running. "
                        "You should start the server first and then run the NEMU again.\n" ANSI_NONE,
           server_name);
}

static bool is_vim_connected = true;

static void vim_execute_cmd(const char *cmd, bool *is_connected, const char *server_name)
{
    int ret = system(cmd);
    if (ret != 0)
    {
        vim_print_error_info(server_name);
        *is_connected = false;
    }
}

void disasm_init_vim_script(word_t start_addr)
{
    char *current_path = getenv("NEMU_HOME");

    /*
     * We add '\r' to the end of the command to make sure that the
     * 'source' command will be executed in the vim server. It
     * simulates the key press of the 'Enter' key.
     * */
    snprintf(cmd, sizeof(cmd), "vim --servername %s --remote-send "
                               "\":source %s/src/utils/%s\"\r",
             vim_server_name, current_path, vim_script_name);

    /* Load the vim script to the disassembly vim server */
    vim_execute_cmd(cmd, &is_vim_connected, vim_server_name);
    if (!is_vim_connected)
        return;

    /* Highlight the cpu start address */
    snprintf(cmd, sizeof(cmd), "vim --servername %s --remote-send "
                               "\":call HighlightAddress(\'" FMT_WORD "\')\"\r",
             vim_server_name, start_addr);

    vim_execute_cmd(cmd, &is_vim_connected, vim_server_name);
}

/*
 * Position the cursor and highlight the disassembly file
 * generated by the gdb disassemble command.
 *
 * DON'T use it in trace_and_difftest() function, executing
 * a large number of system() may cause you Linux unstable.
 *
 * In fact, you only need to call this function after finishing
 * 'si N' command.
 *
 * Parameters:
 * - addr: the address of the executed instruction just now
 */
void disasm_pos_and_hl(word_t addr)
{
    if (!is_vim_connected)
    {
        return;
    }

    snprintf(cmd, sizeof(cmd), "vim --servername %s --remote-send "
                               "\":call HighlightAddress(\'" FMT_WORD "\')\"\r",
             vim_server_name, addr);

    vim_execute_cmd(cmd, &is_vim_connected, vim_server_name);
}

#endif // CONFIG_VIM_AUTO_JUMP